In [13]:
import pandas as pd
import seaborn as sns
from dotenv import load_dotenv
from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
)

In [2]:
sns.set_style('whitegrid')

In [3]:
load_dotenv()

True

In [4]:
# # Download latest version
#
# path = kagglehub.competition_download('playground-series-s6e9',
#                                       output_dir='data/ev_purchase',
#                                       )
#
# print("Path to competition files:", path)

In [5]:
test = pd.read_csv('data/ev_purchase/test.csv', index_col='id')
train = pd.read_csv('data/ev_purchase/train.csv', index_col='id')

In [6]:
train.head(10)

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
id,,,,,,,,,,,,,,
0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
5,50,95938.0,55.1,2,8,15,3.0,Other,Urban,Sedan,No,No,Low,No
6,55,109219.0,42.9,1,1,5,4.0,Male,Suburban,Sedan,Yes,Yes,Low,Yes
7,45,60796.0,52.2,2,13,3,2.0,Other,Urban,SUV,No,Yes,Medium,No
8,39,67725.0,31.5,2,11,3,2.0,Female,Urban,Sedan,No,Yes,Medium,No
9,57,114827.0,66.9,2,0,1,5.0,Male,Rural,Sedan,Yes,Yes,Low,Yes

In [12]:
cat_columns = train.select_dtypes(include=str).columns
# we need check unique values in categorical columns to see if there are any inconsistencies

train[cat_columns].nunique()

Gender                    3
City_Type                 3
Current_Car_Type          4
Home_Charging_Possible    2
Subsidy_Available         2
Range_Anxiety_Level       3
Will_Buy_EV               2
dtype: int64

In [17]:
bool_cols = ['Gender', 'Home_Charging_Possible', 'Subsidy_Available']

label_encoder = LabelEncoder()
for col in bool_cols:
    train[col] = label_encoder.fit_transform(train[col])
    test[col] = label_encoder.transform(test[col])

In [18]:
train.head(10)

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
id,,,,,,,,,,,,,,
0,66,92887.0,23.4,2,3,7,1.0,1,Suburban,Sedan,1,0,Low,0
1,38,30000.0,5.0,1,2,2,4.0,1,Rural,SUV,1,0,Low,0
2,26,94389.0,36.8,1,8,15,5.0,0,Urban,Sedan,0,1,Low,1
3,66,73580.0,23.7,2,6,9,3.0,1,Suburban,Hatchback,1,0,Low,0
4,54,57898.0,50.8,1,2,3,3.0,1,Suburban,Hatchback,1,0,Low,0
5,50,95938.0,55.1,2,8,15,3.0,2,Urban,Sedan,0,0,Low,0
6,55,109219.0,42.9,1,1,5,4.0,1,Suburban,Sedan,1,1,Low,1
7,45,60796.0,52.2,2,13,3,2.0,2,Urban,SUV,0,1,Medium,0
8,39,67725.0,31.5,2,11,3,2.0,0,Urban,Sedan,0,1,Medium,0
9,57,114827.0,66.9,2,0,1,5.0,1,Rural,Sedan,1,1,Low,1

In [24]:
one_hot_encoder = OneHotEncoder()

one_hot_columns = ['City_Type', 'Current_Car_Type']

train_encoded = one_hot_encoder.fit_transform(train[one_hot_columns]).toarray()
test_encoded = one_hot_encoder.transform(test[one_hot_columns]).toarray()

columns = one_hot_encoder.get_feature_names_out(one_hot_columns)

train = pd.DataFrame(train_encoded, columns=columns)
test = pd.DataFrame(test_encoded, columns=columns)

In [25]:
train.head(10)

,City_Type_Rural,City_Type_Suburban,City_Type_Urban,Current_Car_Type_Hatchback,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,1.0,0.0
6,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7,0.0,0.0,1.0,0.0,1.0,0.0,0.0
8,0.0,0.0,1.0,0.0,0.0,1.0,0.0
9,1.0,0.0,0.0,0.0,0.0,1.0,0.0